version: '3'

services:
  db:
    build: 
      context: ./db
    ports: 
      - "3306:3306"
    volumes: 
      - ./db/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db
    ports: 
      - "8080:80"

  web:
    build: 
      context: ./web
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./web/src:/var/www/html